services:
  mosquitto:
    build:
      context: ./infra/mosquitto
      dockerfile: Dockerfile
    container_name: wheelsense_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      # Publish a QoS1 probe; exit code proves broker+auth path
      test: ["CMD-SHELL", "mosquitto_pub -h 127.0.0.1 -p 1883 -u dev -P devpass -t 'wheelsense/healthcheck' -q 1 -m ok >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: ./apps/api
    container_name: wheelsense_api
    restart: unless-stopped
    env_file: .env
    depends_on:
      mosquitto:
        condition: service_healthy
    ports:
      - "8000:8000"
    # NOTE: no "command:" override → use Dockerfile CMD (uvicorn)

  web:
    build: ./apps/web
    container_name: wheelsense_web
    restart: unless-stopped
    env_file: .env
    depends_on:
      mosquitto:
        condition: service_healthy
      api:
        condition: service_started
    ports:
      - "3000:3000"
    # NOTE: no "command:" override → use Dockerfile CMD (next dev)

volumes:
  mosquitto_data:
  mosquitto_log:
