services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: wheelsense_mosquitto
    ports:
      - "1883:1883"
    env_file: .env
    environment:
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
    volumes:
      - ./infra/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    # Create/fix pwfile permissions, then start broker
    command: >
      sh -c "
      install -d -m 0700 /mosquitto/data &&
      if [ ! -f /mosquitto/data/pwfile ]; then
        touch /mosquitto/data/pwfile &&
        mosquitto_passwd -b /mosquitto/data/pwfile \"$${MQTT_USER}\" \"$${MQTT_PASS}\";
      fi &&
      chown mosquitto:mosquitto /mosquitto/data/pwfile &&
      chmod 0600 /mosquitto/data/pwfile &&
      exec mosquitto -c /mosquitto/config/mosquitto.conf
      "
    healthcheck:
      # Robust: subscribe once, then publish, wait for delivery (no $SYS headaches)
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 6s
      retries: 7
    restart: unless-stopped

  api:
    build:
      context: ./apps/api
    container_name: wheelsense_api
    env_file: .env
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "8000:8000"
    depends_on:
      mosquitto:
        condition: service_healthy
    # Use Python (already in the image) for a tiny HTTP GET
    healthcheck:
      test:
        - CMD-SHELL
        - >
          python - <<'PY'
          import sys,urllib.request
          try:
              r=urllib.request.urlopen('http://localhost:8000/health',timeout=3)
              sys.exit(0 if r.status==200 else 1)
          except Exception:
              sys.exit(1)
          PY
      interval: 10s
      timeout: 6s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
    container_name: wheelsense_web
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - TZ=Asia/Bangkok
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    # Use Node's built-in fetch (Node 18+) for a quick probe
    healthcheck:
      test:
        - CMD-SHELL
        - >
          node -e "fetch('http://localhost:3000').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
      interval: 10s
      timeout: 6s
      retries: 5
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
